apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
type: Opaque
stringData:
  USER_DB_DSN: "host=postgres-dev user=messager_user password=messager_password dbname=messager_users sslmode=disable"
  MSG_DB_DSN: "host=postgres-dev user=messager_user password=messager_password dbname=messager_messages sslmode=disable"
