apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messager
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - postgres-init-cm.yaml
  - minio.yaml
  - s3-csi.yaml
  - migrate-users-job.yaml
  - migrate-messages-job.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml

configMapGenerator:
  - name: users-migrations-cm
    files:
      - user-service/migrations/001_init.sql
  - name: messages-migrations-cm
    files:
      - message-service/migrations/001_init.sql
      - message-service/migrations/002_add_file_name.sql
generatorOptions:
  disableNameSuffixHash: true
